// Generated by gencpp from file xarm_msgs/MoveAxisAngleRequest.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_MOVEAXISANGLEREQUEST_H
#define XARM_MSGS_MESSAGE_MOVEAXISANGLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_msgs
{
template <class ContainerAllocator>
struct MoveAxisAngleRequest_
{
  typedef MoveAxisAngleRequest_<ContainerAllocator> Type;

  MoveAxisAngleRequest_()
    : pose()
    , mvvelo(0.0)
    , mvacc(0.0)
    , mvtime(0.0)
    , coord(0)
    , relative(0)  {
    }
  MoveAxisAngleRequest_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , mvvelo(0.0)
    , mvacc(0.0)
    , mvtime(0.0)
    , coord(0)
    , relative(0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _pose_type;
  _pose_type pose;

   typedef float _mvvelo_type;
  _mvvelo_type mvvelo;

   typedef float _mvacc_type;
  _mvacc_type mvacc;

   typedef float _mvtime_type;
  _mvtime_type mvtime;

   typedef int16_t _coord_type;
  _coord_type coord;

   typedef int16_t _relative_type;
  _relative_type relative;





  typedef boost::shared_ptr< ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveAxisAngleRequest_

typedef ::xarm_msgs::MoveAxisAngleRequest_<std::allocator<void> > MoveAxisAngleRequest;

typedef boost::shared_ptr< ::xarm_msgs::MoveAxisAngleRequest > MoveAxisAngleRequestPtr;
typedef boost::shared_ptr< ::xarm_msgs::MoveAxisAngleRequest const> MoveAxisAngleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xarm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'xarm_msgs': ['/home/stepjam/catkin_ws/src/xarm_ros/xarm_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f222fa2eeda5e2b5482505e275dcd88";
  }

  static const char* value(const ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f222fa2eeda5e2bULL;
  static const uint64_t static_value2 = 0x5482505e275dcd88ULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_msgs/MoveAxisAngleRequest";
  }

  static const char* value(const ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
float32[] pose\n\
\n\
\n\
\n\
float32 mvvelo\n\
\n\
\n\
\n\
float32 mvacc\n\
\n\
\n\
\n\
float32 mvtime\n\
\n\
\n\
\n\
int16 coord\n\
\n\
\n\
\n\
int16 relative\n\
\n\
";
  }

  static const char* value(const ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.mvvelo);
      stream.next(m.mvacc);
      stream.next(m.mvtime);
      stream.next(m.coord);
      stream.next(m.relative);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveAxisAngleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_msgs::MoveAxisAngleRequest_<ContainerAllocator>& v)
  {
    s << indent << "pose[]" << std::endl;
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      s << indent << "  pose[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pose[i]);
    }
    s << indent << "mvvelo: ";
    Printer<float>::stream(s, indent + "  ", v.mvvelo);
    s << indent << "mvacc: ";
    Printer<float>::stream(s, indent + "  ", v.mvacc);
    s << indent << "mvtime: ";
    Printer<float>::stream(s, indent + "  ", v.mvtime);
    s << indent << "coord: ";
    Printer<int16_t>::stream(s, indent + "  ", v.coord);
    s << indent << "relative: ";
    Printer<int16_t>::stream(s, indent + "  ", v.relative);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_MSGS_MESSAGE_MOVEAXISANGLEREQUEST_H
