// Generated by gencpp from file xarm_msgs/PlayTrajRequest.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_PLAYTRAJREQUEST_H
#define XARM_MSGS_MESSAGE_PLAYTRAJREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_msgs
{
template <class ContainerAllocator>
struct PlayTrajRequest_
{
  typedef PlayTrajRequest_<ContainerAllocator> Type;

  PlayTrajRequest_()
    : traj_file()
    , repeat_times(0)
    , speed_factor(0)  {
    }
  PlayTrajRequest_(const ContainerAllocator& _alloc)
    : traj_file(_alloc)
    , repeat_times(0)
    , speed_factor(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _traj_file_type;
  _traj_file_type traj_file;

   typedef int16_t _repeat_times_type;
  _repeat_times_type repeat_times;

   typedef int16_t _speed_factor_type;
  _speed_factor_type speed_factor;





  typedef boost::shared_ptr< ::xarm_msgs::PlayTrajRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_msgs::PlayTrajRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlayTrajRequest_

typedef ::xarm_msgs::PlayTrajRequest_<std::allocator<void> > PlayTrajRequest;

typedef boost::shared_ptr< ::xarm_msgs::PlayTrajRequest > PlayTrajRequestPtr;
typedef boost::shared_ptr< ::xarm_msgs::PlayTrajRequest const> PlayTrajRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_msgs::PlayTrajRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_msgs::PlayTrajRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xarm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'xarm_msgs': ['/home/stepjam/catkin_ws/src/xarm_ros/xarm_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::PlayTrajRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::PlayTrajRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::PlayTrajRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::PlayTrajRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::PlayTrajRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::PlayTrajRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_msgs::PlayTrajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5cc25d7fcc3dc3c27c76051b595cd231";
  }

  static const char* value(const ::xarm_msgs::PlayTrajRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5cc25d7fcc3dc3c2ULL;
  static const uint64_t static_value2 = 0x7c76051b595cd231ULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_msgs::PlayTrajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_msgs/PlayTrajRequest";
  }

  static const char* value(const ::xarm_msgs::PlayTrajRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_msgs::PlayTrajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
\n\
\n\
string traj_file\n\
int16 repeat_times\n\
int16 speed_factor\n\
\n\
";
  }

  static const char* value(const ::xarm_msgs::PlayTrajRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_msgs::PlayTrajRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.traj_file);
      stream.next(m.repeat_times);
      stream.next(m.speed_factor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlayTrajRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_msgs::PlayTrajRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_msgs::PlayTrajRequest_<ContainerAllocator>& v)
  {
    s << indent << "traj_file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.traj_file);
    s << indent << "repeat_times: ";
    Printer<int16_t>::stream(s, indent + "  ", v.repeat_times);
    s << indent << "speed_factor: ";
    Printer<int16_t>::stream(s, indent + "  ", v.speed_factor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_MSGS_MESSAGE_PLAYTRAJREQUEST_H
