// Generated by gencpp from file xarm_msgs/SetLoadRequest.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_SETLOADREQUEST_H
#define XARM_MSGS_MESSAGE_SETLOADREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_msgs
{
template <class ContainerAllocator>
struct SetLoadRequest_
{
  typedef SetLoadRequest_<ContainerAllocator> Type;

  SetLoadRequest_()
    : mass(0.0)
    , xc(0.0)
    , yc(0.0)
    , zc(0.0)  {
    }
  SetLoadRequest_(const ContainerAllocator& _alloc)
    : mass(0.0)
    , xc(0.0)
    , yc(0.0)
    , zc(0.0)  {
  (void)_alloc;
    }



   typedef float _mass_type;
  _mass_type mass;

   typedef float _xc_type;
  _xc_type xc;

   typedef float _yc_type;
  _yc_type yc;

   typedef float _zc_type;
  _zc_type zc;





  typedef boost::shared_ptr< ::xarm_msgs::SetLoadRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_msgs::SetLoadRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetLoadRequest_

typedef ::xarm_msgs::SetLoadRequest_<std::allocator<void> > SetLoadRequest;

typedef boost::shared_ptr< ::xarm_msgs::SetLoadRequest > SetLoadRequestPtr;
typedef boost::shared_ptr< ::xarm_msgs::SetLoadRequest const> SetLoadRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_msgs::SetLoadRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_msgs::SetLoadRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xarm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'xarm_msgs': ['/home/stepjam/catkin_ws/src/xarm_ros/xarm_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::SetLoadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::SetLoadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::SetLoadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::SetLoadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::SetLoadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::SetLoadRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_msgs::SetLoadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf0aabb9bc326642906923b34f30e4dc";
  }

  static const char* value(const ::xarm_msgs::SetLoadRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf0aabb9bc326642ULL;
  static const uint64_t static_value2 = 0x906923b34f30e4dcULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_msgs::SetLoadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_msgs/SetLoadRequest";
  }

  static const char* value(const ::xarm_msgs::SetLoadRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_msgs::SetLoadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
float32 mass\n\
\n\
\n\
float32 xc\n\
float32 yc\n\
float32 zc\n\
\n\
";
  }

  static const char* value(const ::xarm_msgs::SetLoadRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_msgs::SetLoadRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mass);
      stream.next(m.xc);
      stream.next(m.yc);
      stream.next(m.zc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLoadRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_msgs::SetLoadRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_msgs::SetLoadRequest_<ContainerAllocator>& v)
  {
    s << indent << "mass: ";
    Printer<float>::stream(s, indent + "  ", v.mass);
    s << indent << "xc: ";
    Printer<float>::stream(s, indent + "  ", v.xc);
    s << indent << "yc: ";
    Printer<float>::stream(s, indent + "  ", v.yc);
    s << indent << "zc: ";
    Printer<float>::stream(s, indent + "  ", v.zc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_MSGS_MESSAGE_SETLOADREQUEST_H
