// Generated by gencpp from file xarm_msgs/SetMultipleIntsRequest.msg
// DO NOT EDIT!


#ifndef XARM_MSGS_MESSAGE_SETMULTIPLEINTSREQUEST_H
#define XARM_MSGS_MESSAGE_SETMULTIPLEINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_msgs
{
template <class ContainerAllocator>
struct SetMultipleIntsRequest_
{
  typedef SetMultipleIntsRequest_<ContainerAllocator> Type;

  SetMultipleIntsRequest_()
    : data_int()  {
    }
  SetMultipleIntsRequest_(const ContainerAllocator& _alloc)
    : data_int(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _data_int_type;
  _data_int_type data_int;





  typedef boost::shared_ptr< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetMultipleIntsRequest_

typedef ::xarm_msgs::SetMultipleIntsRequest_<std::allocator<void> > SetMultipleIntsRequest;

typedef boost::shared_ptr< ::xarm_msgs::SetMultipleIntsRequest > SetMultipleIntsRequestPtr;
typedef boost::shared_ptr< ::xarm_msgs::SetMultipleIntsRequest const> SetMultipleIntsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xarm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'xarm_msgs': ['/home/stepjam/catkin_ws/src/xarm_ros/xarm_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "44acdf287a0679e58f3ebc0c5712b826";
  }

  static const char* value(const ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x44acdf287a0679e5ULL;
  static const uint64_t static_value2 = 0x8f3ebc0c5712b826ULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_msgs/SetMultipleIntsRequest";
  }

  static const char* value(const ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
int16[] data_int\n\
\n\
";
  }

  static const char* value(const ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data_int);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMultipleIntsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_msgs::SetMultipleIntsRequest_<ContainerAllocator>& v)
  {
    s << indent << "data_int[]" << std::endl;
    for (size_t i = 0; i < v.data_int.size(); ++i)
    {
      s << indent << "  data_int[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.data_int[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_MSGS_MESSAGE_SETMULTIPLEINTSREQUEST_H
